#!/bin/bash
#SBATCH -N 4
#SBATCH -C knl
#SBATCH -q debug
#SBATCH -J FlameCyl
#SBATCH -t 00:30:00
#SBATCH -A m3406

#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread


#run the application:
srun -n 256 -c 4 --cpu_bind=cores PeleLM3d.intel.mic-knl.MPI.ex inputs.3d-regt
