#!/bin/bash
#SBATCH -N 8
#SBATCH -C knl
#SBATCH -q premium
#SBATCH -J FlameCyl
#SBATCH -t 13:00:00
#SNATCH -A m3406


#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread


#run the application:
srun -n 512 -c 4 --cpu_bind=cores PeleLM3d.intel.mic-knl.MPI.ex inputs.3d-regt
