#!/bin/bash
#SBATCH --nodes=10
#SBATCH --ntasks-per-node=52
#SBATCH -C knl
#SBATCH -q debug
#SBATCH -J FlameCyl
#SBATCH -t 00:30:00


#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread


#run the application:
srun PeleLM3d.intel.mic-knl.MPI.ex inputs.3d-regt
