AMREX_HOME ?= ../../Submodules/amrex
USE_EB = FALSE
PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

DIM        = 2
#DIM       = 3

COMP	   = gnu

USE_PARTICLES = TRUE

USE_MPI    = TRUE
USE_OMP    = FALSE

Bpack   := ./Make.package 
Blocs   := . 

include ../../Submodules/amrex/Tutorials/Amr/Advection_AmrLevel/Exec/Make.Adv
